import type { Task } from "./types";

export type ModelQuality = Record<Task, number>;

export type Model = {
  id: string;
  name: string;
  tag: string;
  paramsLabel: string;
  weightsGB: number;
  kvKiB: number;
  stateGB: number;
  maxContext: number;
  activeB: number;
  totalB: number;
  moe: boolean;
  vision: boolean;
  thinking: boolean;
  mtp: boolean;
  license: string;
  blurb: string;
  quality: ModelQuality;
};

function q(
  chat: number,
  code: number,
  reason: number,
  vision: number,
  docs: number,
): ModelQuality {
  return { chat, code, reason, vision, docs };
}

export const MODELS: Model[] = [
  {
    id: "qwen3.5-0.8b",
    name: "Qwen3.5 0.8B",
    tag: "qwen3.5:0.8b",
    paramsLabel: "0.8B",
    weightsGB: 1.1,
    kvKiB: 8,
    stateGB: 0.02,
    maxContext: 262144,
    activeB: 0.8,
    totalB: 0.8,
    moe: false,
    vision: true,
    thinking: true,
    mtp: false,
    license: "Apache 2.0",
    blurb: "Tiny multimodal model for machines with very little memory.",
    quality: q(34, 30, 32, 36, 34),
  },
  {
    id: "llama3.2-3b",
    name: "Llama 3.2 3B",
    tag: "llama3.2:3b",
    paramsLabel: "3B",
    weightsGB: 2,
    kvKiB: 112,
    stateGB: 0,
    maxContext: 131072,
    activeB: 3,
    totalB: 3,
    moe: false,
    vision: false,
    thinking: false,
    mtp: false,
    license: "Llama license",
    blurb: "Small general model. Quick, and light on disk.",
    quality: q(48, 42, 44, 0, 40),
  },
  {
    id: "qwen3.5-4b",
    name: "Qwen3.5 4B",
    tag: "qwen3.5:4b",
    paramsLabel: "4B",
    weightsGB: 3.4,
    kvKiB: 16,
    stateGB: 0.03,
    maxContext: 262144,
    activeB: 4,
    totalB: 4,
    moe: false,
    vision: true,
    thinking: true,
    mtp: false,
    license: "Apache 2.0",
    blurb: "Small vision model with a long context and a light memory bill.",
    quality: q(56, 50, 54, 60, 58),
  },
  {
    id: "gemma4-e2b",
    name: "Gemma 4 E2B",
    tag: "gemma4:e2b",
    paramsLabel: "E2B",
    weightsGB: 4.6,
    kvKiB: 10,
    stateGB: 0.25,
    maxContext: 131072,
    activeB: 2.3,
    totalB: 5.1,
    moe: false,
    vision: true,
    thinking: true,
    mtp: true,
    license: "Gemma license",
    blurb: "Edge-sized Gemma that also reads images and audio.",
    quality: q(52, 46, 50, 58, 52),
  },
  {
    id: "qwen2.5-coder-7b",
    name: "Qwen2.5 Coder 7B",
    tag: "qwen2.5-coder:7b",
    paramsLabel: "7B",
    weightsGB: 4.7,
    kvKiB: 56,
    stateGB: 0,
    maxContext: 32768,
    activeB: 7,
    totalB: 7,
    moe: false,
    vision: false,
    thinking: false,
    mtp: false,
    license: "Apache 2.0",
    blurb: "The coding model that still fits an 8 GB graphics card.",
    quality: q(58, 72, 54, 0, 48),
  },
  {
    id: "llama3.1-8b",
    name: "Llama 3.1 8B",
    tag: "llama3.1:8b",
    paramsLabel: "8B",
    weightsGB: 4.9,
    kvKiB: 128,
    stateGB: 0,
    maxContext: 131072,
    activeB: 8,
    totalB: 8,
    moe: false,
    vision: false,
    thinking: false,
    mtp: false,
    license: "Llama license",
    blurb: "A widely supported 8B baseline. Newer small models usually beat it.",
    quality: q(60, 54, 56, 0, 50),
  },
  {
    id: "deepseek-r1-8b",
    name: "DeepSeek R1 8B",
    tag: "deepseek-r1:8b",
    paramsLabel: "8B",
    weightsGB: 5.2,
    kvKiB: 128,
    stateGB: 0,
    maxContext: 131072,
    activeB: 8,
    totalB: 8,
    moe: false,
    vision: false,
    thinking: true,
    mtp: false,
    license: "MIT",
    blurb: "Small reasoning model. It thinks in writing before it answers.",
    quality: q(62, 58, 76, 0, 52),
  },
  {
    id: "gemma4-e4b",
    name: "Gemma 4 E4B",
    tag: "gemma4:e4b",
    paramsLabel: "E4B",
    weightsGB: 5.5,
    kvKiB: 12,
    stateGB: 0.35,
    maxContext: 131072,
    activeB: 4.5,
    totalB: 8,
    moe: false,
    vision: true,
    thinking: true,
    mtp: true,
    license: "Gemma license",
    blurb: "Compact Gemma with image and audio input, sized for an 8 GB card.",
    quality: q(64, 56, 62, 70, 62),
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5 9B",
    tag: "qwen3.5:9b",
    paramsLabel: "9B",
    weightsGB: 5.7,
    kvKiB: 32,
    stateGB: 0.05,
    maxContext: 262144,
    activeB: 9,
    totalB: 9,
    moe: false,
    vision: true,
    thinking: true,
    mtp: false,
    license: "Apache 2.0",
    blurb: "Best everyday model on an 8 GB graphics card: chat, tools, and images.",
    quality: q(76, 66, 74, 78, 80),
  },
  {
    id: "gemma4-12b",
    name: "Gemma 4 12B",
    tag: "gemma4:12b",
    paramsLabel: "12B",
    weightsGB: 7.6,
    kvKiB: 16,
    stateGB: 0.5,
    maxContext: 262144,
    activeB: 12,
    totalB: 12,
    moe: false,
    vision: true,
    thinking: true,
    mtp: true,
    license: "Gemma license",
    blurb: "Dense 12B with vision, tools, and a long window. The 12 GB sweet spot.",
    quality: q(78, 66, 74, 80, 80),
  },
  {
    id: "qwen2.5-coder-14b",
    name: "Qwen2.5 Coder 14B",
    tag: "qwen2.5-coder:14b",
    paramsLabel: "14B",
    weightsGB: 9,
    kvKiB: 192,
    stateGB: 0,
    maxContext: 32768,
    activeB: 14,
    totalB: 14,
    moe: false,
    vision: false,
    thinking: false,
    mtp: false,
    license: "Apache 2.0",
    blurb: "Mid-size coder for when the 30B coding model does not fit.",
    quality: q(64, 80, 60, 0, 52),
  },
  {
    id: "deepseek-r1-14b",
    name: "DeepSeek R1 14B",
    tag: "deepseek-r1:14b",
    paramsLabel: "14B",
    weightsGB: 9,
    kvKiB: 192,
    stateGB: 0,
    maxContext: 131072,
    activeB: 14,
    totalB: 14,
    moe: false,
    vision: false,
    thinking: true,
    mtp: false,
    license: "MIT",
    blurb: "Mid-size reasoning distill. Stronger at hard problems than at small talk.",
    quality: q(66, 62, 80, 0, 55),
  },
  {
    id: "gpt-oss-20b",
    name: "gpt-oss 20B",
    tag: "gpt-oss:20b",
    paramsLabel: "20B \u00b7 3.6B active",
    weightsGB: 11.6,
    kvKiB: 24,
    stateGB: 0,
    maxContext: 131072,
    activeB: 3.6,
    totalB: 21,
    moe: true,
    vision: false,
    thinking: true,
    mtp: false,
    license: "Apache 2.0",
    blurb: "OpenAI's open 20B mixture-of-experts. Fits a 16 GB card and stays quick.",
    quality: q(84, 70, 86, 0, 82),
  },
  {
    id: "gemma4-26b",
    name: "Gemma 4 26B",
    tag: "gemma4:26b",
    paramsLabel: "26B \u00b7 ~4B active",
    weightsGB: 17,
    kvKiB: 18,
    stateGB: 0.6,
    maxContext: 262144,
    activeB: 4,
    totalB: 26,
    moe: true,
    vision: true,
    thinking: true,
    mtp: true,
    license: "Gemma license",
    blurb: "Mixture-of-experts Gemma: 26B quality, closer to a small model's speed.",
    quality: q(82, 72, 80, 84, 84),
  },
  {
    id: "qwen3.8-27b",
    name: "Qwen3.8 27B",
    tag: "qwen3.8:27b",
    paramsLabel: "27B",
    weightsGB: 16.5,
    kvKiB: 64,
    stateGB: 0.16,
    maxContext: 262144,
    activeB: 27,
    totalB: 27,
    moe: false,
    vision: true,
    thinking: true,
    mtp: true,
    license: "Apache 2.0",
    blurb: "Newest dense Qwen. The model to run on a 24 GB card for chat, code, and images.",
    quality: q(93, 84, 92, 91, 88),
  },
  {
    id: "qwen3-coder-30b",
    name: "Qwen3 Coder 30B",
    tag: "qwen3-coder:30b",
    paramsLabel: "30B \u00b7 3.3B active",
    weightsGB: 18.6,
    kvKiB: 96,
    stateGB: 0,
    maxContext: 262144,
    activeB: 3.3,
    totalB: 30,
    moe: true,
    vision: false,
    thinking: true,
    mtp: false,
    license: "Apache 2.0",
    blurb: "The local coding model to pick when you have a 24 GB card.",
    quality: q(78, 94, 80, 0, 86),
  },
  {
    id: "deepseek-r1-32b",
    name: "DeepSeek R1 32B",
    tag: "deepseek-r1:32b",
    paramsLabel: "32B",
    weightsGB: 19,
    kvKiB: 256,
    stateGB: 0,
    maxContext: 131072,
    activeB: 32,
    totalB: 32,
    moe: false,
    vision: false,
    thinking: true,
    mtp: false,
    license: "MIT",
    blurb: "Large reasoning distill. The cache is heavy, so the window must stay short.",
    quality: q(80, 74, 88, 0, 60),
  },
  {
    id: "qwen3.6-35b",
    name: "Qwen3.6 35B",
    tag: "qwen3.6:35b",
    paramsLabel: "35B \u00b7 3B active",
    weightsGB: 22.1,
    kvKiB: 20,
    stateGB: 0.07,
    maxContext: 262144,
    activeB: 3,
    totalB: 35,
    moe: true,
    vision: false,
    thinking: true,
    mtp: true,
    license: "Apache 2.0",
    blurb: "Big mixture-of-experts that still fits a 24 GB card and generates quickly.",
    quality: q(83, 82, 84, 0, 86),
  },
  {
    id: "llama3.3-70b",
    name: "Llama 3.3 70B",
    tag: "llama3.3:70b",
    paramsLabel: "70B",
    weightsGB: 42.5,
    kvKiB: 320,
    stateGB: 0,
    maxContext: 131072,
    activeB: 70,
    totalB: 70,
    moe: false,
    vision: false,
    thinking: false,
    mtp: false,
    license: "Llama license",
    blurb: "Strong general 70B. Needs about 48 GB of fast memory before context.",
    quality: q(92, 78, 86, 0, 80),
  },
  {
    id: "gpt-oss-120b",
    name: "gpt-oss 120B",
    tag: "gpt-oss:120b",
    paramsLabel: "117B \u00b7 5.1B active",
    weightsGB: 62.8,
    kvKiB: 36,
    stateGB: 0,
    maxContext: 131072,
    activeB: 5.1,
    totalB: 117,
    moe: true,
    vision: false,
    thinking: true,
    mtp: false,
    license: "Apache 2.0",
    blurb: "The largest practical open mixture-of-experts here. Needs roughly 64 GB of fast memory.",
    quality: q(96, 90, 96, 0, 94),
  }
];

export function modelById(id: string): Model | undefined {
  return MODELS.find((model) => model.id === id);
}
