/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AmslerRouteImport } from './routes/amsler'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as EnRouteImport } from './routes/en'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IolRouteImport } from './routes/iol'
import { Route as JaRouteImport } from './routes/ja'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UrgentRouteImport } from './routes/urgent'
import { Route as ZhCNRouteImport } from './routes/zh-CN'
import { Route as ZhHansRouteImport } from './routes/zh-Hans'
import { Route as CCatIdRouteImport } from './routes/c.$catId'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnSplatRouteImport } from './routes/en.$'
import { Route as JaIndexRouteImport } from './routes/ja.index'
import { Route as JaSplatRouteImport } from './routes/ja.$'
import { Route as TTopicIdRouteImport } from './routes/t.$topicId'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as ZhCNIndexRouteImport } from './routes/zh-CN.index'
import { Route as ZhCNSplatRouteImport } from './routes/zh-CN.$'
import { Route as ZhHansIndexRouteImport } from './routes/zh-Hans.index'
import { Route as ZhHansSplatRouteImport } from './routes/zh-Hans.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AmslerRoute = AmslerRouteImport.update({
  id: '/amsler',
  path: '/amsler',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IolRoute = IolRouteImport.update({
  id: '/iol',
  path: '/iol',
  getParentRoute: () => rootRouteImport,
} as any)
const JaRoute = JaRouteImport.update({
  id: '/ja',
  path: '/ja',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgentRoute = UrgentRouteImport.update({
  id: '/urgent',
  path: '/urgent',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCNRoute = ZhCNRouteImport.update({
  id: '/zh-CN',
  path: '/zh-CN',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansRoute = ZhHansRouteImport.update({
  id: '/zh-Hans',
  path: '/zh-Hans',
  getParentRoute: () => rootRouteImport,
} as any)
const CCatIdRoute = CCatIdRouteImport.update({
  id: '/c/$catId',
  path: '/c/$catId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnSplatRoute = EnSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EnRoute,
} as any)
const JaIndexRoute = JaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JaRoute,
} as any)
const JaSplatRoute = JaSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => JaRoute,
} as any)
const TTopicIdRoute = TTopicIdRouteImport.update({
  id: '/t/$topicId',
  path: '/t/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/$toolId',
  path: '/$toolId',
  getParentRoute: () => ToolsRoute,
} as any)
const ZhCNIndexRoute = ZhCNIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhCNRoute,
} as any)
const ZhCNSplatRoute = ZhCNSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ZhCNRoute,
} as any)
const ZhHansIndexRoute = ZhHansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhHansRoute,
} as any)
const ZhHansSplatRoute = ZhHansSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ZhHansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/amsler': typeof AmslerRoute
  '/clinic': typeof ClinicRoute
  '/en': typeof EnRouteWithChildren
  '/install': typeof InstallRoute
  '/iol': typeof IolRoute
  '/ja': typeof JaRouteWithChildren
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRouteWithChildren
  '/urgent': typeof UrgentRoute
  '/zh-CN': typeof ZhCNRouteWithChildren
  '/zh-Hans': typeof ZhHansRouteWithChildren
  '/c/$catId': typeof CCatIdRoute
  '/en/$': typeof EnSplatRoute
  '/ja/$': typeof JaSplatRoute
  '/t/$topicId': typeof TTopicIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/zh-CN/$': typeof ZhCNSplatRoute
  '/zh-Hans/$': typeof ZhHansSplatRoute
  '/en/': typeof EnIndexRoute
  '/ja/': typeof JaIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/zh-CN/': typeof ZhCNIndexRoute
  '/zh-Hans/': typeof ZhHansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/amsler': typeof AmslerRoute
  '/clinic': typeof ClinicRoute
  '/install': typeof InstallRoute
  '/iol': typeof IolRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/urgent': typeof UrgentRoute
  '/c/$catId': typeof CCatIdRoute
  '/en/$': typeof EnSplatRoute
  '/ja/$': typeof JaSplatRoute
  '/t/$topicId': typeof TTopicIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/zh-CN/$': typeof ZhCNSplatRoute
  '/zh-Hans/$': typeof ZhHansSplatRoute
  '/en': typeof EnIndexRoute
  '/ja': typeof JaIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/zh-CN': typeof ZhCNIndexRoute
  '/zh-Hans': typeof ZhHansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/amsler': typeof AmslerRoute
  '/clinic': typeof ClinicRoute
  '/en': typeof EnRouteWithChildren
  '/install': typeof InstallRoute
  '/iol': typeof IolRoute
  '/ja': typeof JaRouteWithChildren
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRouteWithChildren
  '/urgent': typeof UrgentRoute
  '/zh-CN': typeof ZhCNRouteWithChildren
  '/zh-Hans': typeof ZhHansRouteWithChildren
  '/c/$catId': typeof CCatIdRoute
  '/en/$': typeof EnSplatRoute
  '/ja/$': typeof JaSplatRoute
  '/t/$topicId': typeof TTopicIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/zh-CN/$': typeof ZhCNSplatRoute
  '/zh-Hans/$': typeof ZhHansSplatRoute
  '/en/': typeof EnIndexRoute
  '/ja/': typeof JaIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/zh-CN/': typeof ZhCNIndexRoute
  '/zh-Hans/': typeof ZhHansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/amsler'
    | '/clinic'
    | '/en'
    | '/install'
    | '/iol'
    | '/ja'
    | '/legal'
    | '/privacy'
    | '/qr'
    | '/resources'
    | '/saved'
    | '/search'
    | '/tools'
    | '/urgent'
    | '/zh-CN'
    | '/zh-Hans'
    | '/c/$catId'
    | '/en/$'
    | '/ja/$'
    | '/t/$topicId'
    | '/tools/$toolId'
    | '/zh-CN/$'
    | '/zh-Hans/$'
    | '/en/'
    | '/ja/'
    | '/tools/'
    | '/zh-CN/'
    | '/zh-Hans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/amsler'
    | '/clinic'
    | '/install'
    | '/iol'
    | '/legal'
    | '/privacy'
    | '/qr'
    | '/resources'
    | '/saved'
    | '/search'
    | '/urgent'
    | '/c/$catId'
    | '/en/$'
    | '/ja/$'
    | '/t/$topicId'
    | '/tools/$toolId'
    | '/zh-CN/$'
    | '/zh-Hans/$'
    | '/en'
    | '/ja'
    | '/tools'
    | '/zh-CN'
    | '/zh-Hans'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/amsler'
    | '/clinic'
    | '/en'
    | '/install'
    | '/iol'
    | '/ja'
    | '/legal'
    | '/privacy'
    | '/qr'
    | '/resources'
    | '/saved'
    | '/search'
    | '/tools'
    | '/urgent'
    | '/zh-CN'
    | '/zh-Hans'
    | '/c/$catId'
    | '/en/$'
    | '/ja/$'
    | '/t/$topicId'
    | '/tools/$toolId'
    | '/zh-CN/$'
    | '/zh-Hans/$'
    | '/en/'
    | '/ja/'
    | '/tools/'
    | '/zh-CN/'
    | '/zh-Hans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AmslerRoute: typeof AmslerRoute
  ClinicRoute: typeof ClinicRoute
  EnRoute: typeof EnRouteWithChildren
  InstallRoute: typeof InstallRoute
  IolRoute: typeof IolRoute
  JaRoute: typeof JaRouteWithChildren
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  QrRoute: typeof QrRoute
  ResourcesRoute: typeof ResourcesRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UrgentRoute: typeof UrgentRoute
  ZhCNRoute: typeof ZhCNRouteWithChildren
  ZhHansRoute: typeof ZhHansRouteWithChildren
  CCatIdRoute: typeof CCatIdRoute
  TTopicIdRoute: typeof TTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amsler': {
      id: '/amsler'
      path: '/amsler'
      fullPath: '/amsler'
      preLoaderRoute: typeof AmslerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iol': {
      id: '/iol'
      path: '/iol'
      fullPath: '/iol'
      preLoaderRoute: typeof IolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja': {
      id: '/ja'
      path: '/ja'
      fullPath: '/ja'
      preLoaderRoute: typeof JaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgent': {
      id: '/urgent'
      path: '/urgent'
      fullPath: '/urgent'
      preLoaderRoute: typeof UrgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-CN': {
      id: '/zh-CN'
      path: '/zh-CN'
      fullPath: '/zh-CN'
      preLoaderRoute: typeof ZhCNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-Hans': {
      id: '/zh-Hans'
      path: '/zh-Hans'
      fullPath: '/zh-Hans'
      preLoaderRoute: typeof ZhHansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$catId': {
      id: '/c/$catId'
      path: '/c/$catId'
      fullPath: '/c/$catId'
      preLoaderRoute: typeof CCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/$': {
      id: '/en/$'
      path: '/$'
      fullPath: '/en/$'
      preLoaderRoute: typeof EnSplatRouteImport
      parentRoute: typeof EnRoute
    }
    '/ja/': {
      id: '/ja/'
      path: '/'
      fullPath: '/ja/'
      preLoaderRoute: typeof JaIndexRouteImport
      parentRoute: typeof JaRoute
    }
    '/ja/$': {
      id: '/ja/$'
      path: '/$'
      fullPath: '/ja/$'
      preLoaderRoute: typeof JaSplatRouteImport
      parentRoute: typeof JaRoute
    }
    '/t/$topicId': {
      id: '/t/$topicId'
      path: '/t/$topicId'
      fullPath: '/t/$topicId'
      preLoaderRoute: typeof TTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/zh-CN/': {
      id: '/zh-CN/'
      path: '/'
      fullPath: '/zh-CN/'
      preLoaderRoute: typeof ZhCNIndexRouteImport
      parentRoute: typeof ZhCNRoute
    }
    '/zh-CN/$': {
      id: '/zh-CN/$'
      path: '/$'
      fullPath: '/zh-CN/$'
      preLoaderRoute: typeof ZhCNSplatRouteImport
      parentRoute: typeof ZhCNRoute
    }
    '/zh-Hans/': {
      id: '/zh-Hans/'
      path: '/'
      fullPath: '/zh-Hans/'
      preLoaderRoute: typeof ZhHansIndexRouteImport
      parentRoute: typeof ZhHansRoute
    }
    '/zh-Hans/$': {
      id: '/zh-Hans/$'
      path: '/$'
      fullPath: '/zh-Hans/$'
      preLoaderRoute: typeof ZhHansSplatRouteImport
      parentRoute: typeof ZhHansRoute
    }
  }
}

interface EnRouteChildren {
  EnSplatRoute: typeof EnSplatRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnSplatRoute: EnSplatRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface JaRouteChildren {
  JaSplatRoute: typeof JaSplatRoute
  JaIndexRoute: typeof JaIndexRoute
}

const JaRouteChildren: JaRouteChildren = {
  JaSplatRoute: JaSplatRoute,
  JaIndexRoute: JaIndexRoute,
}

const JaRouteWithChildren = JaRoute._addFileChildren(JaRouteChildren)

interface ToolsRouteChildren {
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsToolIdRoute: ToolsToolIdRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface ZhCNRouteChildren {
  ZhCNSplatRoute: typeof ZhCNSplatRoute
  ZhCNIndexRoute: typeof ZhCNIndexRoute
}

const ZhCNRouteChildren: ZhCNRouteChildren = {
  ZhCNSplatRoute: ZhCNSplatRoute,
  ZhCNIndexRoute: ZhCNIndexRoute,
}

const ZhCNRouteWithChildren = ZhCNRoute._addFileChildren(ZhCNRouteChildren)

interface ZhHansRouteChildren {
  ZhHansSplatRoute: typeof ZhHansSplatRoute
  ZhHansIndexRoute: typeof ZhHansIndexRoute
}

const ZhHansRouteChildren: ZhHansRouteChildren = {
  ZhHansSplatRoute: ZhHansSplatRoute,
  ZhHansIndexRoute: ZhHansIndexRoute,
}

const ZhHansRouteWithChildren =
  ZhHansRoute._addFileChildren(ZhHansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AmslerRoute: AmslerRoute,
  ClinicRoute: ClinicRoute,
  EnRoute: EnRouteWithChildren,
  InstallRoute: InstallRoute,
  IolRoute: IolRoute,
  JaRoute: JaRouteWithChildren,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  QrRoute: QrRoute,
  ResourcesRoute: ResourcesRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UrgentRoute: UrgentRoute,
  ZhCNRoute: ZhCNRouteWithChildren,
  ZhHansRoute: ZhHansRouteWithChildren,
  CCatIdRoute: CCatIdRoute,
  TTopicIdRoute: TTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
