/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmslerRouteImport } from './routes/amsler'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IolRouteImport } from './routes/iol'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QrRouteImport } from './routes/qr'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UrgentRouteImport } from './routes/urgent'
import { Route as CCatIdRouteImport } from './routes/c.$catId'
import { Route as TTopicIdRouteImport } from './routes/t.$topicId'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmslerRoute = AmslerRouteImport.update({
  id: '/amsler',
  path: '/amsler',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IolRoute = IolRouteImport.update({
  id: '/iol',
  path: '/iol',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgentRoute = UrgentRouteImport.update({
  id: '/urgent',
  path: '/urgent',
  getParentRoute: () => rootRouteImport,
} as any)
const CCatIdRoute = CCatIdRouteImport.update({
  id: '/c/$catId',
  path: '/c/$catId',
  getParentRoute: () => rootRouteImport,
} as any)
const TTopicIdRoute = TTopicIdRouteImport.update({
  id: '/t/$topicId',
  path: '/t/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/$toolId',
  path: '/$toolId',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amsler': typeof AmslerRoute
  '/clinic': typeof ClinicRoute
  '/install': typeof InstallRoute
  '/iol': typeof IolRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRouteWithChildren
  '/urgent': typeof UrgentRoute
  '/c/$catId': typeof CCatIdRoute
  '/t/$topicId': typeof TTopicIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amsler': typeof AmslerRoute
  '/clinic': typeof ClinicRoute
  '/install': typeof InstallRoute
  '/iol': typeof IolRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/urgent': typeof UrgentRoute
  '/c/$catId': typeof CCatIdRoute
  '/t/$topicId': typeof TTopicIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amsler': typeof AmslerRoute
  '/clinic': typeof ClinicRoute
  '/install': typeof InstallRoute
  '/iol': typeof IolRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRouteWithChildren
  '/urgent': typeof UrgentRoute
  '/c/$catId': typeof CCatIdRoute
  '/t/$topicId': typeof TTopicIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amsler'
    | '/clinic'
    | '/install'
    | '/iol'
    | '/legal'
    | '/privacy'
    | '/qr'
    | '/saved'
    | '/search'
    | '/tools'
    | '/urgent'
    | '/c/$catId'
    | '/t/$topicId'
    | '/tools/$toolId'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amsler'
    | '/clinic'
    | '/install'
    | '/iol'
    | '/legal'
    | '/privacy'
    | '/qr'
    | '/saved'
    | '/search'
    | '/urgent'
    | '/c/$catId'
    | '/t/$topicId'
    | '/tools/$toolId'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/amsler'
    | '/clinic'
    | '/install'
    | '/iol'
    | '/legal'
    | '/privacy'
    | '/qr'
    | '/saved'
    | '/search'
    | '/tools'
    | '/urgent'
    | '/c/$catId'
    | '/t/$topicId'
    | '/tools/$toolId'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmslerRoute: typeof AmslerRoute
  ClinicRoute: typeof ClinicRoute
  InstallRoute: typeof InstallRoute
  IolRoute: typeof IolRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  QrRoute: typeof QrRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UrgentRoute: typeof UrgentRoute
  CCatIdRoute: typeof CCatIdRoute
  TTopicIdRoute: typeof TTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amsler': {
      id: '/amsler'
      path: '/amsler'
      fullPath: '/amsler'
      preLoaderRoute: typeof AmslerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iol': {
      id: '/iol'
      path: '/iol'
      fullPath: '/iol'
      preLoaderRoute: typeof IolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgent': {
      id: '/urgent'
      path: '/urgent'
      fullPath: '/urgent'
      preLoaderRoute: typeof UrgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$catId': {
      id: '/c/$catId'
      path: '/c/$catId'
      fullPath: '/c/$catId'
      preLoaderRoute: typeof CCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$topicId': {
      id: '/t/$topicId'
      path: '/t/$topicId'
      fullPath: '/t/$topicId'
      preLoaderRoute: typeof TTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsToolIdRoute: ToolsToolIdRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmslerRoute: AmslerRoute,
  ClinicRoute: ClinicRoute,
  InstallRoute: InstallRoute,
  IolRoute: IolRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  QrRoute: QrRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UrgentRoute: UrgentRoute,
  CCatIdRoute: CCatIdRoute,
  TTopicIdRoute: TTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
